### ISSUE TITLE
TA Meeting - Update Repo according to Template

### ISSUE THREAD

**Issue by cer-hunter** [aarnphm/tinymorph#95]
Hey, just going through and checking your repo I noticed it's not based on Dr. Smith's capstone template repo. I would _highly_ recommend that you update the repo to reflect the template (it would've been nice if you cloned the repo from the template to begin with but oh well). It will help expediate my grading and make your repo way more readable.

Best,
Hunter

**Comment by aarnphm** [comment]
Oh, for the folder structure I was following the best-practices for a monorepo with js and python. I also have a threads email with Dr. Smiths regarding to this.

I did mention the structure for the docs as well as the code structure in the [`ExceptionGranted.md`](https://github.com/aarnphm/tinymorph/blob/main/ExceptionGranted.md), I'm not entirely sure how we should proceed with this.

**Comment by aarnphm** [comment]
References.bib is also available under `docs/contents/Reference.bib`

**Comment by cer-hunter** [comment]
oh if you have express permission from Dr. Smith thats fine, I was just going through all the teams who didn't have the template as some teams weren't even aware of the template

**Comment by aarnphm** [comment]
oh i was aware of the templates. I decide not to use it given that our docs are written in markdown. That's all.

**Comment by aarnphm** [comment]
hi @cer-hunter just out of curiosity, but do you mark our content based on the markdown file?

i notice that the viewer on GitHub doesn't render most of the writing correctly, so if you are marking based on the git source I can also render pdf if that works better for you?

**Comment by cer-hunter** [comment]
hey @aarnphm yeah we mark in the git source, cause technically I shouldn't have to download any of your documentation... but yeah if rendering a pdf would make more sense than fixing it, do whatever you think will work best!

**Comment by aarnphm** [comment]
Hmm, I see. Because the link to bibtex, wikilinks, and backlinks are implemented to render on the website.

Let me think a bit about this, will also include the PDF if that is better

**Comment by smiths** [comment]
@aarnphm as we discussed, you are required to use the standard template.  The folder structure should match that in the capTemplate repo.  The file names should match the capTemplate repo.  You can use markdown instead of LaTeX.  You can add files to the folder structure, but the TAs and other reviewers need to be able to quickly find the artifacts that we grade and review.

A quick look shows your docs are in a slightly different place (https://github.com/aarnphm/tinymorph/tree/main/docs/content).  This information is recorded in [ExceptionsGranted](https://github.com/aarnphm/tinymorph/blob/main/ExceptionGranted.md).

This looks fine to me, but I might have missed something.  If you have any concerns @cer-hunter, please let me know.
